name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nim-light-client-wasm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/build-nix-dev-shell

      - name: Run Nim Beacon Chain Light Client WebAssembly tests
        run: nix develop -c yarn test-emcc

  circom-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/build-nix-dev-shell

      - name: Run circom tests
        run: cd beacon-light-client/circom && nix develop -c yarn hardhat test
